services:
  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: notes
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: postgres
    expose:
      - "5432"
    image: postgres:14-alpine
    networks:
      default: null
    ports:
      - target: 5432
        published: "5432"
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - postgres-data:/var/lib/postgresql/data/
networks:
  default:
    name: _default
volumes: 
  postgres-data: